# Table of contents

* [Intro](README.md)

## Enumeration

* [Passive Information Gathering](enumeration/passive-information-gathering.md)
* [Active Information Gathering](enumeration/active-information-gathering.md)
* [Ports](enumeration/ports/README.md)
  * [Nmap](enumeration/ports/nmap.md)
  * [21 - FTP](enumeration/ports/21-ftp.md)
  * [22 - SSH](enumeration/ports/ssh.md)
  * [23 - Telnet](enumeration/ports/23-telnet.md)
  * [25, 587 - SMTP](enumeration/ports/25-587-smtp.md)
  * [53 - DNS](enumeration/ports/dns.md)
  * [69 - TFTP (UDP)](enumeration/ports/69-tftp-udp.md)
  * [79 - finger](enumeration/ports/79-finger.md)
  * [80 / 443 / 8080 - HTTP(S)](enumeration/ports/80-443-8080-http-s.md)
  * [88 - Kerberos](enumeration/ports/88-kerberos.md)
  * [110, 995 - POP + POP (SSL)](enumeration/ports/110-995-pop-+-pop-ssl.md)
  * [111 - RPC / PortMapper](enumeration/ports/111-rpc-portmapper.md)
  * [111, 2049 - NFS](enumeration/ports/111-2049-nfs.md)
  * [113 - ident](enumeration/ports/113-ident.md)
  * [119 - NNTP](enumeration/ports/119-nntp.md)
  * [135 - MSRPC](enumeration/ports/135-msrpc.md)
  * [139, 445 - SMB](enumeration/ports/smb.md)
  * [143 - IMAP](enumeration/ports/143-imap.md)
  * [161, 162 (UDP) - SNMP](enumeration/ports/161-162-udp-snmp.md)
  * [389, 636 - LDAP](enumeration/ports/389-636-ldap.md)
  * [Page](enumeration/ports/page.md)
  * [873 - rsync](enumeration/ports/873-rsync.md)
  * [1050, 1098, 1099 - Java RMI](enumeration/ports/1050-1098-1099-java-rmi.md)
  * [1435 - MSSQL](enumeration/ports/1435-mssql.md)
  * [1978 Unisql](enumeration/ports/1978-unisql.md)
  * [2375 - Docker](enumeration/ports/2375-docker.md)
  * [3128 - Squid](enumeration/ports/3128-squid.md)
  * [3306 - MySQL](enumeration/ports/3306-mysql.md)
  * [3389 - RDP](enumeration/ports/3389-rdp.md)
  * [3690 - Subversion](enumeration/ports/3690-subversion.md)
  * [4369 - Erlang](enumeration/ports/4369-erlang.md)
  * [5555 - ADB](enumeration/ports/5555-adb.md)
  * [5800, 5801, 5900, 5901 - VNC](enumeration/ports/5800-5801-5900-5901-vnc.md)
  * [5432, 5435 - PostgreSQL](enumeration/ports/5432-5435-postgresql.md)
  * [5984, 6984 - CouchDB](enumeration/ports/5984-6984-couchdb.md)
  * [5985, 5986 - WinRM](enumeration/ports/5985-5986-winrm.md)
  * [6000 - X11](enumeration/ports/6000-x11.md)
  * [6379 - Redis](enumeration/ports/6379-redis.md)
  * [8089 - Splunk](enumeration/ports/8089-splunk.md)
  * [9200 - ElasticSearch](enumeration/ports/9200-elasticsearch.md)
  * [27017-19, 27080, 28017 - MongoDB](enumeration/ports/27017-19-27080-28017-mongodb.md)
  * [Werkzeug](enumeration/ports/werkzeug.md)
  * [IRC](enumeration/ports/irc.md)
  * [10000, 20000 - Webmin/Usermin](enumeration/ports/10000-20000-webmin-usermin.md)
  * [IPMI (UDP)](enumeration/ports/ipmi-udp.md)
* [Web attacks](enumeration/web-pentesting/README.md)
  * [Tools](enumeration/web-pentesting/tools.md)
  * [Fixing web exploits](enumeration/web-pentesting/fixing-web-exploits.md)
  * [Fuzzing / Bruteforcing](enumeration/web-pentesting/fuzzing-bruteforcing.md)
  * [SQL injection (SQLi)](enumeration/web-pentesting/sql-injection-sqli/README.md)
    * [MSSQL](enumeration/web-pentesting/sql-injection-sqli/mssql.md)
    * [Scripts](enumeration/web-pentesting/sql-injection-sqli/scripts.md)
    * [PostgreSQLi](enumeration/web-pentesting/sql-injection-sqli/postgresqli.md)
    * [Sqlmap](enumeration/web-pentesting/sql-injection-sqli/sqlmap.md)
    * [SQLite](enumeration/web-pentesting/sql-injection-sqli/sqlite.md)
    * [Oracle - sqlplus](enumeration/web-pentesting/sql-injection-sqli/oracle-sqlplus.md)
    * [NoSQLi](enumeration/web-pentesting/sql-injection-sqli/nosqli.md)
    * [H2 Database (Java)](enumeration/web-pentesting/sql-injection-sqli/h2-database-java.md)
  * [Directory Traversal](enumeration/web-pentesting/directory-traversal.md)
  * [LFI](enumeration/web-pentesting/lfi.md)
  * [RFI](enumeration/web-pentesting/rfi.md)
  * [File Upload](enumeration/web-pentesting/file-upload.md)
  * [Authentication](enumeration/web-pentesting/authenticate.md)
  * [Command Injection](enumeration/web-pentesting/command-injection.md)
  * [XSS](enumeration/web-pentesting/xss.md)
  * [XXE](enumeration/web-pentesting/xxe.md)
  * [SSRF](enumeration/web-pentesting/ssrf.md)
  * [SSTI](enumeration/web-pentesting/ssti.md)
  * [API](enumeration/web-pentesting/api.md)
  * [CSRF](enumeration/web-pentesting/csrf.md)
  * [JWT](enumeration/web-pentesting/jwt.md)
  * [IDOR](enumeration/web-pentesting/idor.md)
  * [Type Juggling](enumeration/web-pentesting/type-juggling.md)
  * [Padding Oracle](enumeration/web-pentesting/padding-oracle.md)
  * [Deserialization](enumeration/web-pentesting/deserialization.md)
  * [XPath](enumeration/web-pentesting/xpath.md)
  * [Information Disclosure](enumeration/web-pentesting/information-disclosure.md)
  * [Business Logic](enumeration/web-pentesting/business-logic.md)
  * [CORS](enumeration/web-pentesting/cors.md)
  * [Insecure deserialization](enumeration/web-pentesting/insecure-deserialization.md)
  * [Prototype Pollution](enumeration/web-pentesting/prototype-pollution.md)
  * [HTTP Request Smuggling](enumeration/web-pentesting/http-request-smuggling.md)
  * [HTTP Host Header Attacks](enumeration/web-pentesting/http-host-header-attacks.md)
  * [GraphQL API](enumeration/web-pentesting/graphql-api.md)
  * [Access Control](enumeration/web-pentesting/access-control.md)
  * [Clickjacking (UI Redressing)](enumeration/web-pentesting/clickjacking-ui-redressing.md)
  * [Race Conditions](enumeration/web-pentesting/race-conditions.md)
  * [WebSocket](enumeration/web-pentesting/websocket.md)
  * [Web Cache Deception](enumeration/web-pentesting/web-cache-deception.md)
  * [SOAP](enumeration/web-pentesting/soap.md)
  * [LLM / AI](enumeration/web-pentesting/llm-ai.md)
  * [Others](enumeration/web-pentesting/others.md)
* [Web Technologies](enumeration/web-technologies/README.md)
  * [Wordpress](enumeration/web-technologies/wordpress.md)
  * [Tomcat](enumeration/web-technologies/tomcat.md)
  * [Python](enumeration/web-technologies/python.md)
  * [Jenkins](enumeration/web-technologies/jenkins.md)
  * [Django](enumeration/web-technologies/django.md)
  * [Java](enumeration/web-technologies/java.md)
  * [Javascript](enumeration/web-technologies/javascript.md)
  * [.NET](enumeration/web-technologies/.net.md)
  * [H2 Database](enumeration/web-technologies/h2-database.md)
  * [WebAssembly](enumeration/web-technologies/webassembly.md)
  * [Git](enumeration/web-technologies/git.md)
  * [Webdav](enumeration/web-technologies/webdav.md)
  * [IIS](enumeration/web-technologies/iis.md)
  * [Joomla](enumeration/web-technologies/joomla.md)
  * [Drupal](enumeration/web-technologies/drupal.md)
  * [Magento](enumeration/web-technologies/magento.md)
  * [PHP](enumeration/web-technologies/php.md)
  * [Ruby on Rails](enumeration/web-technologies/ruby-on-rails.md)
  * [LUA/LSP](enumeration/web-technologies/lua-lsp.md)
  * [Grafana](enumeration/web-technologies/grafana.md)
  * [Laravel](enumeration/web-technologies/laravel.md)
  * [GraphQL](enumeration/web-technologies/graphql.md)
  * [NodeJS / Express](enumeration/web-technologies/nodejs-express.md)
* [Other Technologies](enumeration/other-technologies/README.md)
  * [Docker](enumeration/other-technologies/docker.md)
  * [AWS](enumeration/other-technologies/aws.md)
  * [SQLite](enumeration/other-technologies/sqlite.md)
  * [Ansible](enumeration/other-technologies/ansible.md)
  * [Microsoft Office](enumeration/other-technologies/microsoft-office.md)
  * [Inspect code / Debugger](enumeration/other-technologies/inspect-code-debugger.md)
  * [Cloud](enumeration/other-technologies/cloud.md)
  * [GLPI](enumeration/other-technologies/glpi.md)
* [Password cracking](enumeration/passwords.md)
* [Packet sniffing](enumeration/packet-sniffing.md)

## EXPLOITATION

* [Shells](exploitation/shells.md)
* [File transfer](exploitation/file-transfer.md)
* [Client-side attacks](exploitation/client-side-attacks.md)
* [Buffer overflow](exploitation/buffer-overflow.md)

## POST-EXPLOITATION

* [Windows](post-exploitation/windows/README.md)
  * [Commands](post-exploitation/windows/permissions.md)
  * [Exploits](post-exploitation/windows/exploits.md)
  * [AD](post-exploitation/windows/ad/README.md)
    * [Mind Maps](post-exploitation/windows/ad/mind-maps.md)
    * [Initial Access / Breaching](post-exploitation/windows/ad/initial-access-breaching.md)
    * [Enumeration](post-exploitation/windows/ad/enumeration.md)
    * [Authentication](post-exploitation/windows/ad/authentication.md)
    * [Exploitation](post-exploitation/windows/ad/exploitation.md)
    * [Persistence](post-exploitation/windows/ad/persistence.md)
    * [Credential Harvesting](post-exploitation/windows/ad/credential-harvesting.md)
    * [ACL](post-exploitation/windows/ad/acl.md)
    * [ADCS (Active Directory Certificate Services)](post-exploitation/windows/ad/adcs-active-directory-certificate-services.md)
    * [Trusts](post-exploitation/windows/ad/trusts.md)
  * [AV Evasion](post-exploitation/windows/av-evasion.md)
  * [PS](post-exploitation/windows/powershell.md)
  * [Persistence](post-exploitation/windows/persistence.md)
  * [FW Evasion](post-exploitation/windows/fw-evasion.md)
  * [UAC Bypass](post-exploitation/windows/uac-bypass.md)
* [Linux](post-exploitation/linux/README.md)
  * [Commands](post-exploitation/linux/untitled.md)
  * [SUID / groups / privesc](post-exploitation/linux/suid-groups-privesc.md)
  * [Sudo exploitation & CVEs](post-exploitation/linux/sudo-exploitation-and-cves.md)
  * [Persistence](post-exploitation/linux/persistence.md)
* [Port Redirection and Tunneling](post-exploitation/port-redirection-and-tunneling.md)
* [Lateral Movement](post-exploitation/lateral-movement.md)
* [Data exfiltration](post-exploitation/data-exfiltration.md)

## MISC

* [Reverse Engineering](misc/reverse-engineering.md)
* [Cryptography](misc/cryptography.md)
* [Scripting](misc/scripting.md)
* [Stego](misc/stego.md)
* [OSINT](misc/osint.md)
* [Blue Team](misc/blue-team.md)
* [📱 Mobile Pentesting](misc/mobile-pentesting.md)
* [Malware Analysis](misc/malware-analysis.md)
* [Anti-forensics](misc/anti-forensics.md)
* [Curso s4vitar](misc/curso-s4vitar.md)
* [Red Teaming / C2](misc/red-teaming-c2.md)
* [Forensics / Incident Response](misc/forensics-incident-response.md)
* [DevOps](misc/devops.md)
* [Bug Bounty](misc/bug-bounty.md)
* [Road to OSCP](misc/master.md)

## Tools

* [Burp Suite](tools/burp-suite.md)
* [NetExec](tools/netexec.md)
* [Metasploit](tools/metasploit.md)
* [C2 (Command & Control)](tools/empire.md)
* [OWASP ZAP](tools/owasp-zap.md)

## CTFs

* [OverTheWire - Bandit](ctfs/bandit.md)

## RANDOM
